const chatSectionWidth = '300px';

const meetingStyles = {
  participantsContainer: {
    // outline: '2px solid black',
    height: '100vh',
    width: `calc(100% - ${chatSectionWidth})`,
  },
  participants: {
    height: '100%',
    width: '100%',
    // outline: '12px solid red',
  },
  remoteParticipant: {
    // outline: '2px solid blue',
    backgroundColor: '#f5f5f5',
    padding: '10px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: '8px',
    width: ' 100%',
    height: '90%',
    marginBottom: '2px',
  },
  remoteParticipantOrderTwo: {
    // outline: '2px solid blue',
    backgroundColor: '#f5f5f5',
    padding: '10px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    // marginLeft: '8px',
    width: ' 100%',
    height: '50%',
  },
  remoteParticipantOrderThree: {
    // outline: '2px solid blue',
    backgroundColor: '#f5f5f5',
    padding: '10px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    // marginLeft: '8px',
    width: ' 100%',
    height: '30%',
    overflowX: 'auto',
  },
  localParticipant: {
    // outline: '10px solid blue',
    width: ' 100%',
    height: '90%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
    padding: '10px',
  },
  localParticipantOrderTwo: {
    // outline: '10px solid blue',
    width: ' 100%',
    height: '50%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
    padding: '10px',
    marginBottom: '4px',
  },
  localParticipantOrderThree: {
    width: ' 100%',
    height: '70%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
    padding: '10px',
    marginBottom: '4px',
  },

  noRemoteParticipants: {
    height: '100%',
    width: '100%',
    // outline: '12px solid red',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '10px',
    // backgroundColor: 'grey',
  },
  oneRemoteParticipant: {
    height: '100%',
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '10px',
  },
  chatSection: {
    // outline: '1px solid yellow',
    height: '100vh',
    padding: '8px',
    width: chatSectionWidth,
  },
  rootStyles: {
    height: '100%',
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardStyles: {
    height: '100%',
    width: '500px',
    padding: '50px',
  },
  videoContainer: {
    height: '100%',
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: '15px',
    boxShadow: '0px 3px 17px -3px rgb(0 0 0 / 36%)',
    aspectRatio: '4/3',
    backgroundColor: 'black',
  },
  videoStyles: {
    borderRadius: '15px',
    width: '100%',
    height: '100%',
  },
  loaderStyles: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  upperContentStyles: {
    position: 'relative',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  loaderContentStyles: {
    color: 'white',
  },
  loaderTextStyles: {
    marginLeft: '5px',
    color: 'white',
  },
  cardFooter: {
    // outline: '2px solid green',
    marginTop: '30px',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  meetingControlStyles: {
    // outline: '2px solid red',
    backgroundColor: 'primary.main',
    color: 'white',
    margin: '5px',
    borderRadius: '8px',
    '&:hover': {
      backgroundColor: 'primary.light',
    },
  },
  joinMeetingButtonContainerStyle: {
    // outline: '2px solid red',
    flexGrow: '1',
    display: 'flex',
    justifyContent: 'flex-end',
  },
  joinMeetingButtonStyle: {
    width: '200px',
  },
  endMeetingButtonstyle: {
    backgroundColor: 'error.light',
    '&:hover': {
      backgroundColor: 'error.dark',
    },
  },
};

export default meetingStyles;
