import { grey } from '@mui/material/colors';

const chatSectionWidth = '360px';

const meetingStyles = {
  participantsContainer: {
    height: '100vh',
    width: `calc(100% - ${chatSectionWidth})`,
  },
  participants: {
    height: '100%',
    width: '100%',
  },
  remoteParticipant: {
    padding: '10px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: '8px',
    width: ' 100%',
    height: '90%',
    marginBottom: '2px',
  },
  remoteParticipantOrderTwo: {
    padding: '10px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    // marginLeft: '8px',
    width: ' 100%',
    height: '50%',
  },
  remoteParticipantOrderThree: {
    padding: '10px',
    display: 'flex',
    justifyContent: 'flex-start',
    alignItems: 'center',
    width: ' 100%',
    height: '30%',
    overflowX: 'auto',
  },
  localParticipant: {
    width: ' 100%',
    height: '90%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '10px',
  },
  localParticipantOrderTwo: {
    width: ' 100%',
    height: '50%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '10px',
    marginBottom: '4px',
  },
  localParticipantOrderThree: {
    width: ' 100%',
    height: '70%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '10px',
    marginBottom: '4px',
  },

  noRemoteParticipants: {
    height: '100%',
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '10px',
  },
  oneRemoteParticipant: {
    height: '100%',
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '10px',
  },
  chatSection: {
    height: '100vh',
    padding: '8px',
    width: chatSectionWidth,
  },
  rootStyles: {
    height: '100%',
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardStyles: {
    height: '100%',
    width: '100%',
    maxWidth: '500px',
    padding: '5%',
  },
  videoContainer: {
    height: '100%',
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: '15px',
    boxShadow: '0px 3px 17px -3px rgb(0 0 0 / 36%)',
    aspectRatio: '4/3',
    backgroundColor: 'black',
  },
  participantIcon: {
    backgroundColor: (theme) => theme.palette.secondary.dark,
    position: 'absolute',
    left: '50%',
    top: '50%',
    transform: 'translate(-50%, -50%)',
    height: '3em',
    width: '3em',
    borderRadius: '50%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    fontSize: '1.5rem',
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: '2px',
    zIndex: 1,
  },
  videoStyles: {
    borderRadius: '15px',
    width: '100%',
    height: '100%',
  },
  loaderStyles: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  upperContentStyles: {
    position: 'relative',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  loaderContentStyles: {
    color: 'white',
  },
  loaderTextStyles: {
    marginLeft: '0.5em',
    color: 'white',
  },
  cardFooter: {
    marginTop: '30px',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  meetingControls: {
    backgroundColor: 'primary.dark',
    color: 'white',
    margin: '5px',
    borderRadius: '8px',
    '&:hover': {
      backgroundColor: 'primary.main',
    },
  },
  meetingControlsOff: {
    backgroundColor: grey[500],
    '&:hover': {
      backgroundColor: grey[500],
    },
  },
  joinMeetingButtonContainerStyle: {
    flexGrow: '1',
    display: 'flex',
    justifyContent: 'center',
  },
  joinMeetingButtonStyle: {
    width: '100%',
  },
  endMeetingButton: {
    backgroundColor: 'error.main',
    '&:hover': {
      backgroundColor: 'error.light',
    },
  },
};

export default meetingStyles;
